### ISSUE TITLE
dataset

### ISSUE THREAD

**Issue by psriram93** [despoisj/DeepAudioClassification#1]
Hi, I would like to know which dataset you are using for training.

**Comment by despoisj** [comment]
Hi,

As mentioned in the blog post on Medium, I simply used - parts of - my own
iTunes library.

Best regards,

Julien

2016-12-11 15:52 GMT+01:00 psriram93 <notifications@github.com>:

**Comment by psriram93** [comment]
Can you suggest any dataset which might have all the the features like using tags and info? I have found million song dataset's subset but I think it's not enough to train using your kind of training
http://labrosa.ee.columbia.edu/millionsong/

**Comment by despoisj** [comment]
I think this depends on how many genres you aim to distinguish, what accuracy etc. My library was only a couple thousand songs. Unfortunately, I did not explore the available datasets as I relied on my data.

Best,

Julien
