### ISSUE TITLE
Getting predictions out of the model with an input file

### ISSUE THREAD

**Issue by simonfranz** [despoisj/DeepAudioClassification#4]
Hi there, 

I wanted also to play around with your package. Seems to be very nice, clean and easily customizable.
What I'm missung is some prediction method. The end-result of a ml-project is to use the learned model and get some predictions for an inputfile.

Could you maybe add some hints here, where to start to get predictions for an input-file?
The path is clear. First take the input-file, split the input file, load the model, get the predictions for the parts and get and end-result. But I'm not sure how to extend the loadDataset method to get the model and afterwards get the model working with an input file.

Thanks in advance

**Comment by simonfranz** [comment]
I have solved this by myself, sorry for posting so early.
Like I described in my qestion.
* First create a spectogram from the given audio file
* Slice it into the 128x128 image slices and save it with the prefix of the file
* load each image slice with the given prefix with the getImageData method
* append each loaded image to a data-array
* be sure the model is loaded

now get the predictions:
```
model.load('musicDNN.tflearn')
predictionSoftmax = model.predict(data)[0]
predictedIndex = max(enumerate(predictionSoftmax), key=lambda x:x[1])[0]
print "Prediction:", ["{0:.2f}".format(x) for x in predictionSoftmax], "->", predictedIndex
print("The genre is: %s" % genres[predictedIndex])
```

You could also get the prediction by yourself vor every image-silce by your own. This would look similar to this
```
predictionSoftmax = model.predict([data[0])[0]
```
Then you will get the predictions for the first slice. With this you may implement a better voting system.

Thanks to @despoisj for this great starting point to ML

**Comment by despoisj** [comment]
I'm glad you figured that out :) ! 👍
